[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "P"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
